# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todolistapp
  name: todolistapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistapp
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
        - name: todolistapp-container
          image: 980921731940.dkr.ecr.us-east-1.amazonaws.com/my-reepository:27
          imagePullPolicy: Always
          ports:
            - containerPort: 80       # Your app inside the container is running on port 80
              name: http
              protocol: TCP
